# Generated by Django 5.0.4 on 2024-04-08 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('nit', 'NIT'), ('cc', 'Cédula de Ciudadanía')], max_length=3)),
                ('identificacion', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employee.empleado')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('tel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cell', 'Celular'), ('tel', 'Teléfono')], max_length=4)),
                ('numero', models.CharField(max_length=15)),
                ('indicativo', models.CharField(max_length=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='employee.empleado')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
                'db_table': 'telefono',
                'ordering': ['numero'],
            },
        ),
    ]
